/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: dwalsh (https://sketchfab.com/dwalsh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/energy-drink-game-ready-model-83676feb8b0a4589952cf3676299311b
Title: Energy Drink Game Ready Model
*/

import React, { useEffect, useMemo, useRef, useState } from "react";
import { useFrame, useThree } from "@react-three/fiber";
import { useLoader } from "@react-three/fiber";
import { OBJLoader } from "three/examples/jsm/loaders/OBJLoader";
import { useTexture, Billboard } from "@react-three/drei";
import { Color, TextureLoader, RepeatWrapping, MeshStandardMaterial, DoubleSide, PlaneGeometry } from "three";
import { animate } from "framer-motion";
import { easeQuadOut } from "d3-ease";

import { noise } from "./Noise";
import { useStore } from "./store";
import { wines } from "./data";

import model from "./assets/models/jd_bottle_lowpoly.obj?url";
import logoImg from "./assets/logo 2.png";

// Import textures
import baseColorTexture from "./assets/models/Texture/defaultMat_Base_Color.jpg?url";
import normalTexture from "./assets/models/Texture/defaultMat_Normal_DirectX.jpg?url";
import roughnessTexture from "./assets/models/Texture/defaultMat_Roughness.jpg?url";
import metallicTexture from "./assets/models/Texture/defaultMat_Metallic.jpg?url";
import opacityTexture from "./assets/models/Texture/defaultMat_Opacity.jpg?url";
import aoTexture from "./assets/models/Texture/defaultMat_Mixed_AO.jpg?url";

// Function to create a bottle material with a specific color
const createBottleMaterial = (textures, color) => {
  return new MeshStandardMaterial({
    map: textures.map,
    normalMap: textures.normalMap,
    roughnessMap: textures.roughnessMap,
    metalnessMap: textures.metalnessMap,
    aoMap: textures.aoMap,
    transparent: true,
    opacity: 0.9,
    side: DoubleSide,
    envMapIntensity: 0.05,
    roughness: 0.1,
    metalness: 0.2,
    aoMapIntensity: 0.5,
    color: new Color(color)
  });
};

// Debug function to log color in different formats
const debugColor = (color, label = "") => {
  const c = new Color(color);
  console.log(`${label}:`, {
    hex: c.getHexString(),
    rgb: c.toArray(),
    originalValue: color.toString(16)
  });
};

const Bottle = (props) => {
  const obj = useLoader(OBJLoader, model);
  const modelRef = useRef();
  const groupRef = useRef();
  const [current, setCurrent] = useState(0);
  const [currentMaterial, setCurrentMaterial] = useState(null);
  const [isAnimating, setIsAnimating] = useState(false);
  
  // Load textures
  const textures = useTexture({
    map: baseColorTexture,
    normalMap: normalTexture,
    roughnessMap: roughnessTexture,
    metalnessMap: metallicTexture,
    aoMap: aoTexture,
    alphaMap: opacityTexture,
  });

  // Configure texture settings
  Object.values(textures).forEach(texture => {
    texture.wrapS = texture.wrapT = RepeatWrapping;
    texture.anisotropy = 4;
  });

  // Create label material (stays white)
  const labelMaterial = useMemo(() => {
    const mat = new MeshStandardMaterial({
      map: textures.map,
      normalMap: textures.normalMap,
      roughnessMap: textures.roughnessMap,
      metalnessMap: textures.metalnessMap,
      aoMap: textures.aoMap,
      transparent: true,
      opacity: 0.95,
      side: DoubleSide,
      color: new Color(0xFFFFFF) // Keep label white
    });
    return mat;
  }, [textures]);

  const play = useStore((s) => s.play);
  const setCurrentWine = useStore((s) => s.setCurrentWine);
  const triggerBackgroundChange = useStore((s) => s.triggerBackgroundChange);

  // Function to update all bottle meshes with a new material
  const updateBottleMaterial = (newMaterial) => {
    obj.traverse((child) => {
      if (child.isMesh && child.name !== 'Group15797') {
        child.material = newMaterial;
      }
    });
  };

  const handleClick = () => {
    console.log("\n=== Click Handler Triggered ===");
    console.log("Play state:", play);
    console.log("Current index:", current);
    console.log("Is animating:", isAnimating);
    
    if (play && !isAnimating) {
      triggerColorChange();
    } else {
      console.log("Play state is false or already animating, not starting animation");
    }
  };

  // Function to trigger color change (can be called from drag or click)
  const triggerColorChange = () => {
    if (!play || isAnimating) return;
    
    setIsAnimating(true);
    
    let len = wines.length;
    let nextIndex = (current + 1) % len;
    
    console.log("\n=== Color Change Triggered ===");
    console.log("Current index:", current, "Next index:", nextIndex);
    debugColor(wines[current].color, "Current wine color");
    debugColor(wines[nextIndex].color, "Next wine color");

    const currentColor = new Color(wines[current].color);
    const nextColor = new Color(wines[nextIndex].color);

    // Trigger background wave animation immediately with the new color
    triggerBackgroundChange();

    animate(0, 1, {
      onUpdate(v) {
        const newColor = new Color();
        newColor.lerpColors(currentColor, nextColor, v);
        
        // Create new material with interpolated color
        const newMaterial = createBottleMaterial(textures, newColor.getHex());
        setCurrentMaterial(newMaterial);
        updateBottleMaterial(newMaterial);
        
        if (v === 0 || v === 0.5 || v === 1) {
          console.log(`Animation progress ${v * 100}%:`, {
            interpolatedColor: newColor.getHexString(),
            materialColor: newMaterial.color.getHexString()
          });
        }
      },
      onComplete() {
        console.log("\n=== Color Transition Complete ===");
        setCurrent(nextIndex);
        setCurrentWine(wines[nextIndex]);
        
        // Create final material
        const finalMaterial = createBottleMaterial(textures, wines[nextIndex].color);
        setCurrentMaterial(finalMaterial);
        updateBottleMaterial(finalMaterial);
        
        console.log("Final material color:", finalMaterial.color.getHexString());
        
        // Reset animation flag
        setIsAnimating(false);
      },
      duration: 0.3, // Much faster transition (was 2.5)
      ease: easeQuadOut,
    });
  };

  // Handle drag events
  const handleDrag = (event) => {
    console.log("Drag detected on bottle");
    console.log("Is animating:", isAnimating);
    
    if (!isAnimating) {
      // Trigger color change on drag
      triggerColorChange();
    }
  };

  useFrame(({ clock }) => {
    const time = clock.getElapsedTime();
    if (modelRef.current) {
      modelRef.current.position.y = Math.sin(time * 0.8) * 0.08;
      modelRef.current.rotation.y = Math.sin(time * 0.6) * 0.2;
      modelRef.current.rotation.z = Math.sin(time * 0.6) * 0.05;
    }
  });

  useEffect(() => {
    setCurrentWine(wines[0]);
  }, [setCurrentWine]);

  // Initialize materials when textures are loaded
  useEffect(() => {
    if (textures.map && !currentMaterial) {
      const initialMaterial = createBottleMaterial(textures, wines[0].color);
      setCurrentMaterial(initialMaterial);
      console.log("Created initial material with color:", wines[0].color.toString(16));
    }
  }, [textures, currentMaterial]);

  useEffect(() => {
    if (obj && currentMaterial) {
      console.log("\n=== Assigning Materials to Meshes ===");
      let bottleMeshCount = 0;
      let labelMeshCount = 0;
      
      obj.traverse((child) => {
        if (child.isMesh) {
          // Check if this is the label mesh
          if (child.name === 'Group15797') {
            child.material = labelMaterial;
            labelMeshCount++;
            console.log(`Assigned label material to mesh: ${child.name}`);
          } else {
            child.material = currentMaterial;
            bottleMeshCount++;
            console.log(`Assigned bottle material to mesh: ${child.name}`);
            debugColor(currentMaterial.color.getHex(), `Bottle material color for ${child.name}`);
          }
        }
      });
      
      console.log(`Total meshes: ${bottleMeshCount} bottle + ${labelMeshCount} label`);
    }
  }, [obj, currentMaterial, labelMaterial]);

  return (
    <group 
      ref={groupRef} 
      {...props} 
      onClick={handleClick}
      onPointerDown={handleDrag}
    >
      <primitive ref={modelRef} object={obj} scale={3.8} position={[0, -0.3, 0]} />
    </group>
  );
};

// Logo Component
const Logo = () => {
  const logoTexture = useLoader(TextureLoader, logoImg);
  
  return (
    <Billboard
      follow={true}
      lockX={false}
      lockY={false}
      lockZ={false}
    >
      <mesh position={[0, 4.6, -2]}>
        <planeGeometry args={[3.5, 2]} />
        <meshStandardMaterial 
          map={logoTexture} 
          transparent={true} 
          opacity={1}
          side={DoubleSide}
          depthTest={false}
          metalness={0.2}
          roughness={0.0}
          envMapIntensity={0.05}
          // Optional: Add normal map for more texture detail
          // normalMap={normalTexture}
          // normalScale={[0.1, 0.1]}
        />
      </mesh>
    </Billboard>
  );
};

const Model = {
  Bottle,
  Logo
};

export default Model;